name    'adamcrews-newrelic'
version '0.0.1'
source 'git://github.com/adamcrews/puppet-newrelic'
author 'Adam Crews'
license 'Apache License, Version 2.0'
summary 'Newrelic Module'
description 'Newrelic Module to manage the Newrelic system monitor.'
project_page 'https://github.com/adamcrews/puppet-newrelic'
dependency 'puppetlabs/stdlib', '>= 4.3.0'
